### PR TITLE
Bugfixes/diamonds prs

### PR DESCRIPTION
**Pull request by kwarunek**

### CODE REVIEW

**Review by KlavsKlavsen — DISMISSED** [review]
LGTM

**Comment by kwarunek** [comment]
https://github.com/python-diamond/Diamond/pull/701 in

**Comment by kwarunek** [comment]
https://github.com/python-diamond/Diamond/pull/212 in

**Comment by kwarunek** [comment]
https://github.com/python-diamond/Diamond/pull/354 in

**Comment by kwarunek** [comment]
https://github.com/python-diamond/Diamond/pull/353 in

**Comment by kwarunek** [comment]
https://github.com/python-diamond/Diamond/pull/362 in

**Pull request merged**
